### ISSUE TITLE
VSCode Extension v0.0.26 still not working

### ISSUE THREAD

**Issue by carver-mdg** [AvaloniaUI/AvaloniaVSCode#89] opened 2024-01-12 19:48 UTC
Type: <b>Bug</b>

Code completion and preview are not working - always says "Previewer is not available. Build the project first.". I tried close vscode -> build project from terminal -> open vscode. I tried the old versions of expansion, they also did not work.

Build target dotnet 8.

```dotnet --list-sdks```
- 8.0.100 [C:\Program Files\dotnet\sdk]
- 8.0.101 [C:\Program Files\dotnet\sdk]

VSCode Extension:
![extension_always_say_need_build](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/10282794/bfb52b23-dd45-4a0a-a0f3-2f81c874c100)

Code completion:
![code_completion](https://github.com/AvaloniaUI/AvaloniaVSCode/assets/10282794/1077f345-6f27-4d83-a623-449b638585af)

Extension version: 0.0.26
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.34GB (19.47GB free)|
|Process Argv|C:\\projects\\AvaloniaApplication1 --crash-reporter-id e6bedc8e-f7ac-4bab-b84a-d2053dd65313|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by SignalMQ** [comment] 2024-01-13 09:35
Duplicate of issue: https://github.com/AvaloniaUI/AvaloniaVSCode/issues/86

**Closed** 2024-01-18 15:13 UTC

**Comment by ezexe** [comment] 2025-02-06 07:48
this is still happening on macos in vscode
