### ISSUE TITLE
Extension fails to launch child process if VS Code path has spaces

### ISSUE THREAD

**Issue by alexrp** [AvaloniaUI/AvaloniaVSCode#41] opened 2023-09-05 20:49 UTC
```
2023-09-05 22:43:09.681 [info] [EXT - INFO] Solution data path path: C:\Users\ALEXRN~1\AppData\Local\Temp\tests.sln.json
2023-09-05 22:43:10.247 [info] parser process args: C:\WINDOWS\system32\cmd.exe,/d,/s,/c,"dotnet c:\Users\Alex Rønne Petersen\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.17\solutionParserTool\SolutionParser.dll z:\Source\tests\tests.sln"
2023-09-05 22:43:10.345 [info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-c:\Users\Alex does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

2023-09-05 22:43:10.356 [info] parser process exited 1
```

(Note the second bullet point there.)

**Comment by prashantvc** [comment] 2023-09-08 10:30
duplicate of #39

**Closed by prashantvc** 2023-09-08 10:30 UTC
